2022-12-15 21:15:03.786 | DEBUG    | aria2p.api:remove:470 - Try to remove download 0a6635c602761000
2022-12-15 21:15:03.789 | ERROR    | aria2p.api:remove:474 - GID 0a6635c602761000 is not found
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw0-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7fb7cecaf390>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7fb7cedd5080>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7fb7cecd4a90>
    └ <execnet.gateway_base.WorkerGateway object at 0x7fb7cecd47d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7fb7cecd5190>
    │    └ <function WorkerPool._perform_spawn at 0x7fb7cedd5260>
    └ <execnet.gateway_base.WorkerPool object at 0x7fb7cecd4a90>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7fb7cedd4f40>
    └ <execnet.gateway_base.Reply object at 0x7fb7cecd5190>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7fb7cecd47d0>>
    └ <execnet.gateway_base.Reply object at 0x7fb7cecd5190>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x562acdab2a80, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 312, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7fb7cd635510>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7fb7cd631750>
    └ <_pytest.config.Config object at 0x7fb7cd635510>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7fb7cd635510>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fb7ceb2f240>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7fb7cd635510>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7fb7ceb1ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7fb7cd635510>]
          │         └ <function pytest_cmdline_main at 0x7fb7cd884e00>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7fb7cd884d60>
           │            └ <_pytest.config.Config object at 0x7fb7cd635510>
           └ <function wrap_session at 0x7fb7cd884cc0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7fb7cd635510>
    │       │            └ <function _main at 0x7fb7cd884d60>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7fb7cd631750>
    └ <_pytest.config.Config object at 0x7fb7cd635510>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fb7ceb2f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7fb7ceb1ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7fb7cd48d450>>
          └ <HookImpl plugin_name='140427399844944', plugin=<__channelexec__.WorkerInteractor object at 0x7fb7cd48d450>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 112, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [15, 16, 17, 18, 19]
    │    └ <function WorkerInteractor.run_one_test at 0x7fb7cd628b80>
    └ <__channelexec__.WorkerInteractor object at 0x7fb7cd48d450>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 131, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_following_id>
    │    │      │    │                            └ <Function test_remove>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7fb7cd631750>
    │    └ <_pytest.config.Config object at 0x7fb7cd635510>
    └ <__channelexec__.WorkerInteractor object at 0x7fb7cd48d450>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove>, 'nextitem': <Function test_following_id>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fb7ceb2f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove>, 'nextitem': <Function test_following_id>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7fb7ceb1ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove>, <Function test_following_id>]
          │         └ <function pytest_runtest_protocol at 0x7fb7cc90afc0>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_following_id>
              │               └ <Function test_remove>
              └ <function runtestprotocol at 0x7fb7cd87b600>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 131, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove>
    │       │      └ <function call_and_report at 0x7fb7cd87b9c0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_downloads.py::TestDownloadClass::test_remove' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 220, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove>
           └ <function call_runtest_hook at 0x7fb7cd87bba0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 259, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7fb7cd87bec0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 339, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7fb7c5bdb560>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 260, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fb7ceb2f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7fb7ceb1ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove>]
          │         └ <function pytest_runtest_call at 0x7fb7cd87b7e0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 167, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7fb7cd6e02c0>
    └ <Function test_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1789, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove>
    │    └ <property object at 0x7fb7cd7de520>
    └ <Function test_remove>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7fb7ceb2f240>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7fb7ceb1ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7fb7cd6269d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove>]
          │         └ <function pytest_pyfunc_call at 0x7fb7cd8a3880>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'server': <tests.conftest._Aria2Server object at 0x7fb7c5d28f10>}
             └ <bound method TestDownloadClass.test_remove of <tests.test_downloads.TestDownloadClass object at 0x7fb7c65c8550>>

  File "/media/data/dev/aria2p/tests/test_downloads.py", line 313, in test_remove
    self.download.remove()
    │    │        └ <function Download.remove at 0x7fb7cc3ca480>
    │    └ <aria2p.downloads.Download object at 0x7fb7c5d28d10>
    └ <tests.test_downloads.TestDownloadClass object at 0x7fb7c65c8550>

  File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 1026, in remove
    result = self.api.remove([self], force=force, files=files)[0]
             │    │   │       │            │            └ False
             │    │   │       │            └ False
             │    │   │       └ <aria2p.downloads.Download object at 0x7fb7c5d28d10>
             │    │   └ <function API.remove at 0x7fb7cc3cb7e0>
             │    └ API(Client(host='http://localhost', port=15531, secret='********'))
             └ <aria2p.downloads.Download object at 0x7fb7c5d28d10>

> File "/media/data/dev/aria2p/src/aria2p/api.py", line 472, in remove
    removed_gid = remove_func(download.gid)
                  │           │        └ <property object at 0x7fb7cc3ba390>
                  │           └ <aria2p.downloads.Download object at 0x7fb7c5d28d10>
                  └ <bound method Client.remove of Client(host='http://localhost', port=15531, secret='********')>

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 630, in remove
    return self.call(self.REMOVE, [gid])  # type: ignore  # noqa: WPS204 (overused [gid])
           │    │    │    │        └ '0a6635c602761000'
           │    │    │    └ 'aria2.remove'
           │    │    └ Client(host='http://localhost', port=15531, secret='********')
           │    └ <function Client.call at 0x7fb7cc541940>
           └ Client(host='http://localhost', port=15531, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 265, in call
    return self.res_or_raise(self.post(payload))
           │    │            │    │    └ '{"jsonrpc": "2.0", "method": "aria2.remove", "id": -1, "params": ["0a6635c602761000"]}'
           │    │            │    └ <function Client.post at 0x7fb7cc541b20>
           │    │            └ Client(host='http://localhost', port=15531, secret='********')
           │    └ <staticmethod(<function Client.res_or_raise at 0x7fb7cc541c60>)>
           └ Client(host='http://localhost', port=15531, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 392, in res_or_raise
    raise Client.response_as_exception(response)
          │      │                     └ {'id': -1, 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'GID 0a6635c602761000 is not found'}}
          │      └ <staticmethod(<function Client.response_as_exception at 0x7fb7cc541bc0>)>
          └ <class 'aria2p.client.Client'>

aria2p.client.ClientException: GID 0a6635c602761000 is not found
2022-12-15 21:15:03.802 | DEBUG    | aria2p.api:remove:499 - aria2 control file /home/pawamoy/Downloads/torrents/tmp/dl.aria2 was not found
