2022-12-15 21:15:10.208 | DEBUG    | aria2p.api:remove:470 - Try to remove download 0000000000000001
2022-12-15 21:15:10.211 | SUCCESS  | aria2p.api:remove:477 - Removed download 0000000000000001
2022-12-15 21:15:10.213 | DEBUG    | aria2p.api:remove:482 - Failed to remove download result 0000000000000001
2022-12-15 21:15:10.213 | TRACE    | aria2p.api:remove:483 - GID 0000000000000001 is not found
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw3-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f8295b51e90>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f8295cd9080>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
    │    └ <function WorkerPool._perform_spawn at 0x7f8295cd9260>
    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f8295cd8f40>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x564920ed3a80, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 312, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f829473fed0>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f829473fed0>]
          │         └ <function pytest_cmdline_main at 0x7f829471ce00>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f829471cd60>
           │            └ <_pytest.config.Config object at 0x7f829473fed0>
           └ <function wrap_session at 0x7f829471ccc0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7f829473fed0>
    │       │            └ <function _main at 0x7f829471cd60>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
          └ <HookImpl plugin_name='140198724162256', plugin=<__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 112, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [413, 414]
    │    └ <function WorkerInteractor.run_one_test at 0x7f82944b8b80>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 131, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_parse_input_file>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    │    └ <_pytest.config.Config object at 0x7f829473fed0>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_parse_input_file>]
          │         └ <function pytest_runtest_protocol at 0x7f828f7aefc0>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_parse_input_file>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7f8294713600>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 131, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7f82947139c0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 220, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7f8294713ba0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 259, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f8294713ec0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 339, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f828cadaa20>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 260, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7f82947137e0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 167, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f82945702c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1789, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7f82946765c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7f829473b880>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'), 'port': 15330}
             └ <function test_remove_files_not_complete at 0x7f828efbc2c0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 175, in test_remove_files_not_complete
    assert server.api.remove(downloads, files=True)
           │      │   │      └ [<aria2p.downloads.Download object at 0x7f8294c59a10>, <aria2p.downloads.Download object at 0x7f8294c59dd0>]
           │      │   └ <function API.remove at 0x7f828f26b7e0>
           │      └ API(Client(host='http://localhost', port=15330, secret='********'))
           └ <tests.conftest._Aria2Server object at 0x7f828cc45450>

> File "/media/data/dev/aria2p/src/aria2p/api.py", line 480, in remove
    self.client.remove_download_result(download.gid)
    │    │      │                      │        └ <property object at 0x7f828f25de90>
    │    │      │                      └ <aria2p.downloads.Download object at 0x7f8294c59a10>
    │    │      └ <function Client.remove_download_result at 0x7f828f3e6f20>
    │    └ Client(host='http://localhost', port=15330, secret='********')
    └ API(Client(host='http://localhost', port=15330, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 1460, in remove_download_result
    return self.call(self.REMOVE_DOWNLOAD_RESULT, [gid])  # type: ignore
           │    │    │    │                        └ '0000000000000001'
           │    │    │    └ 'aria2.removeDownloadResult'
           │    │    └ Client(host='http://localhost', port=15330, secret='********')
           │    └ <function Client.call at 0x7f828f3e5940>
           └ Client(host='http://localhost', port=15330, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 265, in call
    return self.res_or_raise(self.post(payload))
           │    │            │    │    └ '{"jsonrpc": "2.0", "method": "aria2.removeDownloadResult", "id": -1, "params": ["0000000000000001"]}'
           │    │            │    └ <function Client.post at 0x7f828f3e5b20>
           │    │            └ Client(host='http://localhost', port=15330, secret='********')
           │    └ <staticmethod(<function Client.res_or_raise at 0x7f828f3e5c60>)>
           └ Client(host='http://localhost', port=15330, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 392, in res_or_raise
    raise Client.response_as_exception(response)
          │      │                     └ {'id': -1, 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'GID 0000000000000001 is not found'}}
          │      └ <staticmethod(<function Client.response_as_exception at 0x7f828f3e5bc0>)>
          └ <class 'aria2p.client.Client'>

aria2p.client.ClientException: GID 0000000000000001 is not found
2022-12-15 21:15:10.220 | DEBUG    | aria2p.api:remove:499 - aria2 control file /tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0/5m.aria2 was not found
2022-12-15 21:15:10.220 | WARNING  | aria2p.downloads:root_files_paths:346 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'
2022-12-15 21:15:10.220 | TRACE    | aria2p.downloads:root_files_paths:347 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw3-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f8295b51e90>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f8295cd9080>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
    │    └ <function WorkerPool._perform_spawn at 0x7f8295cd9260>
    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f8295cd8f40>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x564920ed3a80, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 312, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f829473fed0>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f829473fed0>]
          │         └ <function pytest_cmdline_main at 0x7f829471ce00>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f829471cd60>
           │            └ <_pytest.config.Config object at 0x7f829473fed0>
           └ <function wrap_session at 0x7f829471ccc0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7f829473fed0>
    │       │            └ <function _main at 0x7f829471cd60>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
          └ <HookImpl plugin_name='140198724162256', plugin=<__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 112, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [413, 414]
    │    └ <function WorkerInteractor.run_one_test at 0x7f82944b8b80>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 131, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_parse_input_file>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    │    └ <_pytest.config.Config object at 0x7f829473fed0>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_parse_input_file>]
          │         └ <function pytest_runtest_protocol at 0x7f828f7aefc0>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_parse_input_file>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7f8294713600>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 131, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7f82947139c0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 220, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7f8294713ba0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 259, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f8294713ec0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 339, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f828cadaa20>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 260, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7f82947137e0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 167, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f82945702c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1789, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7f82946765c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7f829473b880>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'), 'port': 15330}
             └ <function test_remove_files_not_complete at 0x7f828efbc2c0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 175, in test_remove_files_not_complete
    assert server.api.remove(downloads, files=True)
           │      │   │      └ [<aria2p.downloads.Download object at 0x7f8294c59a10>, <aria2p.downloads.Download object at 0x7f8294c59dd0>]
           │      │   └ <function API.remove at 0x7f828f26b7e0>
           │      └ API(Client(host='http://localhost', port=15330, secret='********'))
           └ <tests.conftest._Aria2Server object at 0x7f828cc45450>

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 504, in remove
    self.remove_files([download], force=True)
    │    │             └ <aria2p.downloads.Download object at 0x7f8294c59a10>
    │    └ <staticmethod(<function API.remove_files at 0x7f828f274040>)>
    └ API(Client(host='http://localhost', port=15330, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 715, in remove_files
    for path in download.root_files_paths:
                │        └ <property object at 0x7f828f25de40>
                └ <aria2p.downloads.Download object at 0x7f8294c59a10>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 344, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7f828f25e840>
                    │    │                └ <aria2p.downloads.Download object at 0x7f8294c59a10>
                    │    └ <property object at 0x7f828f25db20>
                    └ <aria2p.downloads.File object at 0x7f828cb2a150>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/lib/python3.11/pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
2022-12-15 21:15:10.227 | DEBUG    | aria2p.api:remove:470 - Try to remove download 0000000000000002
2022-12-15 21:15:10.230 | SUCCESS  | aria2p.api:remove:477 - Removed download 0000000000000002
2022-12-15 21:15:10.232 | DEBUG    | aria2p.api:remove:482 - Failed to remove download result 0000000000000002
2022-12-15 21:15:10.232 | TRACE    | aria2p.api:remove:483 - GID 0000000000000002 is not found
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw3-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f8295b51e90>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f8295cd9080>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
    │    └ <function WorkerPool._perform_spawn at 0x7f8295cd9260>
    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f8295cd8f40>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x564920ed3a80, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 312, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f829473fed0>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f829473fed0>]
          │         └ <function pytest_cmdline_main at 0x7f829471ce00>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f829471cd60>
           │            └ <_pytest.config.Config object at 0x7f829473fed0>
           └ <function wrap_session at 0x7f829471ccc0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7f829473fed0>
    │       │            └ <function _main at 0x7f829471cd60>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
          └ <HookImpl plugin_name='140198724162256', plugin=<__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 112, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [413, 414]
    │    └ <function WorkerInteractor.run_one_test at 0x7f82944b8b80>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 131, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_parse_input_file>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    │    └ <_pytest.config.Config object at 0x7f829473fed0>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_parse_input_file>]
          │         └ <function pytest_runtest_protocol at 0x7f828f7aefc0>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_parse_input_file>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7f8294713600>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 131, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7f82947139c0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 220, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7f8294713ba0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 259, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f8294713ec0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 339, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f828cadaa20>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 260, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7f82947137e0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 167, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f82945702c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1789, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7f82946765c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7f829473b880>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'), 'port': 15330}
             └ <function test_remove_files_not_complete at 0x7f828efbc2c0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 175, in test_remove_files_not_complete
    assert server.api.remove(downloads, files=True)
           │      │   │      └ [<aria2p.downloads.Download object at 0x7f8294c59a10>, <aria2p.downloads.Download object at 0x7f8294c59dd0>]
           │      │   └ <function API.remove at 0x7f828f26b7e0>
           │      └ API(Client(host='http://localhost', port=15330, secret='********'))
           └ <tests.conftest._Aria2Server object at 0x7f828cc45450>

> File "/media/data/dev/aria2p/src/aria2p/api.py", line 480, in remove
    self.client.remove_download_result(download.gid)
    │    │      │                      │        └ <property object at 0x7f828f25de90>
    │    │      │                      └ <aria2p.downloads.Download object at 0x7f8294c59dd0>
    │    │      └ <function Client.remove_download_result at 0x7f828f3e6f20>
    │    └ Client(host='http://localhost', port=15330, secret='********')
    └ API(Client(host='http://localhost', port=15330, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 1460, in remove_download_result
    return self.call(self.REMOVE_DOWNLOAD_RESULT, [gid])  # type: ignore
           │    │    │    │                        └ '0000000000000002'
           │    │    │    └ 'aria2.removeDownloadResult'
           │    │    └ Client(host='http://localhost', port=15330, secret='********')
           │    └ <function Client.call at 0x7f828f3e5940>
           └ Client(host='http://localhost', port=15330, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 265, in call
    return self.res_or_raise(self.post(payload))
           │    │            │    │    └ '{"jsonrpc": "2.0", "method": "aria2.removeDownloadResult", "id": -1, "params": ["0000000000000002"]}'
           │    │            │    └ <function Client.post at 0x7f828f3e5b20>
           │    │            └ Client(host='http://localhost', port=15330, secret='********')
           │    └ <staticmethod(<function Client.res_or_raise at 0x7f828f3e5c60>)>
           └ Client(host='http://localhost', port=15330, secret='********')

  File "/media/data/dev/aria2p/src/aria2p/client.py", line 392, in res_or_raise
    raise Client.response_as_exception(response)
          │      │                     └ {'id': -1, 'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'GID 0000000000000002 is not found'}}
          │      └ <staticmethod(<function Client.response_as_exception at 0x7f828f3e5bc0>)>
          └ <class 'aria2p.client.Client'>

aria2p.client.ClientException: GID 0000000000000002 is not found
2022-12-15 21:15:10.239 | DEBUG    | aria2p.api:remove:499 - aria2 control file /tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0/6m.aria2 was not found
2022-12-15 21:15:10.239 | WARNING  | aria2p.downloads:root_files_paths:346 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'
2022-12-15 21:15:10.239 | TRACE    | aria2p.downloads:root_files_paths:347 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw3-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f8295b51e90>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f8295cd9080>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
    │    └ <function WorkerPool._perform_spawn at 0x7f8295cd9260>
    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f8295cd8f40>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x564920ed3a80, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 312, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f829473fed0>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f829473fed0>]
          │         └ <function pytest_cmdline_main at 0x7f829471ce00>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f829471cd60>
           │            └ <_pytest.config.Config object at 0x7f829473fed0>
           └ <function wrap_session at 0x7f829471ccc0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7f829473fed0>
    │       │            └ <function _main at 0x7f829471cd60>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
          └ <HookImpl plugin_name='140198724162256', plugin=<__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 112, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [413, 414]
    │    └ <function WorkerInteractor.run_one_test at 0x7f82944b8b80>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 131, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_parse_input_file>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    │    └ <_pytest.config.Config object at 0x7f829473fed0>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_parse_input_file>]
          │         └ <function pytest_runtest_protocol at 0x7f828f7aefc0>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_parse_input_file>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7f8294713600>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 131, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7f82947139c0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 220, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7f8294713ba0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 259, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f8294713ec0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 339, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f828cadaa20>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 260, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7f82947137e0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 167, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f82945702c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1789, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7f82946765c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7f829473b880>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'), 'port': 15330}
             └ <function test_remove_files_not_complete at 0x7f828efbc2c0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 175, in test_remove_files_not_complete
    assert server.api.remove(downloads, files=True)
           │      │   │      └ [<aria2p.downloads.Download object at 0x7f8294c59a10>, <aria2p.downloads.Download object at 0x7f8294c59dd0>]
           │      │   └ <function API.remove at 0x7f828f26b7e0>
           │      └ API(Client(host='http://localhost', port=15330, secret='********'))
           └ <tests.conftest._Aria2Server object at 0x7f828cc45450>

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 504, in remove
    self.remove_files([download], force=True)
    │    │             └ <aria2p.downloads.Download object at 0x7f8294c59dd0>
    │    └ <staticmethod(<function API.remove_files at 0x7f828f274040>)>
    └ API(Client(host='http://localhost', port=15330, secret='********'))

  File "/media/data/dev/aria2p/src/aria2p/api.py", line 715, in remove_files
    for path in download.root_files_paths:
                │        └ <property object at 0x7f828f25de40>
                └ <aria2p.downloads.Download object at 0x7f8294c59dd0>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 344, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7f828f25e840>
                    │    │                └ <aria2p.downloads.Download object at 0x7f8294c59dd0>
                    │    └ <property object at 0x7f828f25db20>
                    └ <aria2p.downloads.File object at 0x7f828cc390d0>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/lib/python3.11/pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
2022-12-15 21:15:10.245 | WARNING  | aria2p.downloads:root_files_paths:346 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'
2022-12-15 21:15:10.245 | TRACE    | aria2p.downloads:root_files_paths:347 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw3-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f8295b51e90>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f8295cd9080>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
    │    └ <function WorkerPool._perform_spawn at 0x7f8295cd9260>
    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f8295cd8f40>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x564920ed3a80, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 312, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f829473fed0>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f829473fed0>]
          │         └ <function pytest_cmdline_main at 0x7f829471ce00>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f829471cd60>
           │            └ <_pytest.config.Config object at 0x7f829473fed0>
           └ <function wrap_session at 0x7f829471ccc0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7f829473fed0>
    │       │            └ <function _main at 0x7f829471cd60>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
          └ <HookImpl plugin_name='140198724162256', plugin=<__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 112, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [413, 414]
    │    └ <function WorkerInteractor.run_one_test at 0x7f82944b8b80>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 131, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_parse_input_file>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    │    └ <_pytest.config.Config object at 0x7f829473fed0>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_parse_input_file>]
          │         └ <function pytest_runtest_protocol at 0x7f828f7aefc0>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_parse_input_file>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7f8294713600>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 131, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7f82947139c0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 220, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7f8294713ba0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 259, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f8294713ec0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 339, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f828cadaa20>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 260, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7f82947137e0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 167, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f82945702c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1789, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7f82946765c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7f829473b880>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'), 'port': 15330}
             └ <function test_remove_files_not_complete at 0x7f828efbc2c0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 177, in test_remove_files_not_complete
    for file in download.root_files_paths:
                │        └ <property object at 0x7f828f25de40>
                └ <aria2p.downloads.Download object at 0x7f8294c59a10>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 344, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7f828f25e840>
                    │    │                └ <aria2p.downloads.Download object at 0x7f8294c59a10>
                    │    └ <property object at 0x7f828f25db20>
                    └ <aria2p.downloads.File object at 0x7f828cb2a150>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/lib/python3.11/pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
2022-12-15 21:15:10.252 | WARNING  | aria2p.downloads:root_files_paths:346 - Can't determine file path '.' relative to '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'
2022-12-15 21:15:10.252 | TRACE    | aria2p.downloads:root_files_paths:347 - '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw3-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f8295b51e90>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f8295cd9080>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
    │    └ <function WorkerPool._perform_spawn at 0x7f8295cd9260>
    └ <execnet.gateway_base.WorkerPool object at 0x7f8295b78990>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f8295cd8f40>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f8295b786d0>>
    └ <execnet.gateway_base.Reply object at 0x7f8295b79110>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x564920ed3a80, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 312, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f829473fed0>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f829473fed0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f829473fed0>]
          │         └ <function pytest_cmdline_main at 0x7f829471ce00>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f829471cd60>
           │            └ <_pytest.config.Config object at 0x7f829473fed0>
           └ <function wrap_session at 0x7f829471ccc0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7f829473fed0>
    │       │            └ <function _main at 0x7f829471cd60>
    │       └ <ExitCode.OK: 0>
    └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    └ <_pytest.config.Config object at 0x7f829473fed0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session config exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
          └ <HookImpl plugin_name='140198724162256', plugin=<__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 112, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [413, 414]
    │    └ <function WorkerInteractor.run_one_test at 0x7f82944b8b80>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 131, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_parse_input_file>
    │    │      │    │                            └ <Function test_remove_files_not_complete>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7f82944c5350>
    │    └ <_pytest.config.Config object at 0x7f829473fed0>
    └ <__channelexec__.WorkerInteractor object at 0x7f828f26d2d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>, 'nextitem': <Function test_parse_input_file>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>, <Function test_parse_input_file>]
          │         └ <function pytest_runtest_protocol at 0x7f828f7aefc0>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_parse_input_file>
              │               └ <Function test_remove_files_not_complete>
              └ <function runtestprotocol at 0x7f8294713600>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 131, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_remove_files_not_complete>
    │       │      └ <function call_and_report at 0x7f82947139c0>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_api.py::test_remove_files_not_complete' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 220, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_remove_files_not_complete>
           └ <function call_runtest_hook at 0x7f8294713ba0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 259, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f8294713ec0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 339, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f828cadaa20>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 260, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_remove_files_not_complete>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_runtest_call at 0x7f82947137e0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 167, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f82945702c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1789, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_remove_files_not_complete>
    │    └ <property object at 0x7f82946765c0>
    └ <Function test_remove_files_not_complete>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8294d7f240>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f82944b6610>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_remove_files_not_complete>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f8294d6ee80>
           └ <_pytest.config.PytestPluginManager object at 0x7f82944b6610>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_remove_files_not_complete>]
          │         └ <function pytest_pyfunc_call at 0x7f829473b880>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'tmp_path': PosixPath('/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0'), 'port': 15330}
             └ <function test_remove_files_not_complete at 0x7f828efbc2c0>

  File "/media/data/dev/aria2p/tests/test_api.py", line 177, in test_remove_files_not_complete
    for file in download.root_files_paths:
                │        └ <property object at 0x7f828f25de40>
                └ <aria2p.downloads.Download object at 0x7f8294c59dd0>

> File "/media/data/dev/aria2p/src/aria2p/downloads.py", line 344, in root_files_paths
    relative_path = file.path.relative_to(self.dir)
                    │    │                │    └ <property object at 0x7f828f25e840>
                    │    │                └ <aria2p.downloads.Download object at 0x7f8294c59dd0>
                    │    └ <property object at 0x7f828f25db20>
                    └ <aria2p.downloads.File object at 0x7f828cc390d0>

  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/lib/python3.11/pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"

ValueError: '.' is not in the subpath of '/tmp/pytest-of-pawamoy/pytest-9/popen-gw3/test_remove_files_not_complete0' OR one path is relative and the other is absolute.
